export default {
  /*二级类目*/
  categorys: [{
    label: '热门',
    options: [{
      name: '热点',
      categoryId: '1'
    }, {
      name: '军事',
      categoryId: '30'
    }, {
      name: '历史',
      categoryId: '31'
    }, {
      name: '明星',
      categoryId: '32'
    }]
  }, {
    label: '科学',
    options: [{
      name: '科技',
      categoryId: '2'
    }, {
      name: '教育',
      categoryId: '3'
    }, {
      name: '数码',
      categoryId: '4'
    }, {
      name: '汽车',
      categoryId: '5'
    }, {
      name: '商业',
      categoryId: '6'
    }]
  }, {
    label: '时尚',
    options: [{
      name: '美容',
      categoryId: '7'
    }, {
      name: '潮流',
      categoryId: '8'
    }, {
      name: '母婴',
      categoryId: '9'
    }, {
      name: '家居',
      categoryId: '10'
    }, {
      name: '旅行',
      categoryId: '27'
    }, {
      name: '品牌',
      categoryId: '28'
    }, {
      name: '艺术',
      categoryId: '33'
    }]
  }, {
    label: '生活',
    options: [{
      name: '健康',
      categoryId: '11'
    }, {
      name: '美食',
      categoryId: '12'
    }, {
      name: '成人',
      categoryId: '13'
    }, {
      name: '技巧',
      categoryId: '14'
    }, {
      name: '房产',
      categoryId: '34'
    }, {
      name: '亲子',
      categoryId: '35'
    }, {
      name: '情感',
      categoryId: '36'
    }, {
      name: '家装',
      categoryId: '37'
    }, {
      name: '创意',
      categoryId: '39'
    }]
  }, {
    label: '娱乐',
    options: [{
      name: '动漫',
      categoryId: '15'
    }, {
      name: '宠物',
      categoryId: '16'
    }, {
      name: '音乐',
      categoryId: '17'
    }, {
      name: '舞蹈',
      categoryId: '18'
    }, {
      name: '电影',
      categoryId: '19'
    }, {
      name: '游戏',
      categoryId: '20'
    }, {
      name: '搞笑',
      categoryId: '26'
    }, {
      name: '星座',
      categoryId: '29'
    }, {
      name: '小品',
      categoryId: '40'
    }]
  }, {
    label: '体育',
    options: [{
      name: '极限',
      categoryId: '21'
    }, {
      name: '球星',
      categoryId: '22'
    }, {
      name: '足球',
      categoryId: '23'
    }, {
      name: '篮球',
      categoryId: '24'
    }, {
      name: '赛车',
      categoryId: '25'
    }, {
      name: '健身',
      categoryId: '38'
    }]
  }]
}
